# Generated by Django 5.2.17 on 2026-09-03 22:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message="El código debe tener la forma 'recurso:accion', solo minúsculas y guiones bajos (ej: tarima:crear).", regex='^[a-z_]+:[a-z_]+$')], verbose_name='código')),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripción')),
                ('dominio', models.CharField(choices=[('contabilidad', 'Contabilidad y finanzas'), ('cuentas', 'Cuentas por cobrar y pagar'), ('facturacion', 'Facturación, ventas y factura electrónica'), ('agricola', 'Agrícola y finca'), ('produccion', 'Producción y empaque'), ('inventario', 'Inventario y bodega'), ('proveeduria', 'Proveeduría y compras'), ('rrhh', 'Recursos humanos y planilla'), ('parqueo', 'Parqueo'), ('sistema', 'Sistema y administración')], max_length=30, verbose_name='dominio')),
            ],
            options={
                'verbose_name': 'permiso',
                'verbose_name_plural': 'permisos',
                'ordering': ['dominio', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=250, verbose_name='descripción')),
                ('pantalla_inicio', models.CharField(blank=True, help_text='Ruta del frontend a la que cae este rol al iniciar sesión.', max_length=100, verbose_name='pantalla de inicio')),
                ('es_superadmin', models.BooleanField(default=False, help_text='Puede asignar roles y ámbitos a otros usuarios.', verbose_name='es superadministrador')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('asignado', 'Asignado'), ('revocado', 'Revocado'), ('reactivado', 'Reactivado')], max_length=20, verbose_name='acción')),
                ('ambito_descripcion', models.CharField(blank=True, help_text='Descripción textual del ámbito al momento de la acción -- asi el registro se sigue entendiendo aunque el ambito se borre despues.', max_length=250, verbose_name='ámbito')),
                ('es_autoasignacion', models.BooleanField(default=False, verbose_name='es autoasignación')),
                ('realizado_en', models.DateTimeField(auto_now_add=True, verbose_name='realizado en')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_como_autor', to=settings.AUTH_USER_MODEL)),
                ('usuario_afectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_como_afectado', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autorizacion.rol')),
            ],
            options={
                'verbose_name': 'entrada de bitácora de permisos',
                'verbose_name_plural': 'bitácora de permisos',
                'ordering': ['-realizado_en'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('asignado_en', models.DateTimeField(auto_now_add=True, verbose_name='asignado en')),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizacion.bodega')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizacion.empresa')),
                ('finca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizacion.finca')),
                ('punto_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizacion.puntoventa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='autorizacion.rol')),
            ],
            options={
                'verbose_name': 'asignación',
                'verbose_name_plural': 'asignaciones',
                'ordering': ['-asignado_en'],
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorizacion.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorizacion.rol')),
            ],
            options={
                'verbose_name': 'permiso de rol',
                'verbose_name_plural': 'permisos de rol',
            },
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(related_name='roles', through='autorizacion.RolPermiso', to='autorizacion.permiso'),
        ),
        migrations.AddConstraint(
            model_name='rolpermiso',
            constraint=models.UniqueConstraint(fields=('rol', 'permiso'), name='permiso_unico_por_rol'),
        ),
    ]
