# Generated by Django 5.2.17 on 2026-09-12 02:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de vehículo',
                'verbose_name_plural': 'tipos de vehículo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_hora', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='monto por hora')),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Lo que se cobra aunque el vehículo salga a los pocos minutos.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='monto mínimo')),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate, verbose_name='vigente desde')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='parqueo.tipovehiculo')),
            ],
            options={
                'verbose_name': 'tarifa',
                'verbose_name_plural': 'tarifas',
                'ordering': ['tipo_vehiculo', '-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(db_index=True, max_length=15, verbose_name='placa')),
                ('hora_ingreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='hora de ingreso')),
                ('hora_salida', models.DateTimeField(blank=True, null=True, verbose_name='hora de salida')),
                ('horas_cobradas', models.PositiveIntegerField(blank=True, null=True, verbose_name='horas cobradas')),
                ('monto_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='monto cobrado')),
                ('estado', models.CharField(choices=[('dentro', 'Dentro'), ('cobrado', 'Cobrado y salió')], default='dentro', max_length=10, verbose_name='estado')),
                ('cobrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros_parqueo', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_parqueo', to='organizacion.empresa')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_registrados', to=settings.AUTH_USER_MODEL)),
                ('tarifa_aplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='parqueo.tarifa')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='parqueo.tipovehiculo')),
            ],
            options={
                'verbose_name': 'ingreso a parqueo',
                'verbose_name_plural': 'ingresos a parqueo',
                'ordering': ['-hora_ingreso'],
            },
        ),
        migrations.AddConstraint(
            model_name='tarifa',
            constraint=models.UniqueConstraint(fields=('tipo_vehiculo', 'vigente_desde'), name='tarifa_unica_por_tipo_y_fecha'),
        ),
        migrations.AddConstraint(
            model_name='ingreso',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'dentro')), fields=('placa', 'empresa'), name='placa_unica_mientras_esta_dentro'),
        ),
    ]
