# Generated by Django 5.2.17 on 2026-09-03 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_juridica', models.CharField(max_length=20, unique=True, verbose_name='cédula jurídica')),
                ('razon_social', models.CharField(max_length=200, verbose_name='razón social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='nombre comercial')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('insumos', 'Insumos agrícolas'), ('empaque', 'Material de empaque'), ('producto_terminado', 'Producto terminado'), ('repuestos', 'Repuestos y mantenimiento'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='tipo')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bodegas', to='organizacion.empresa')),
            ],
            options={
                'verbose_name': 'bodega',
                'verbose_name_plural': 'bodegas',
                'ordering': ['empresa', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nombre'), name='bodega_unica_por_empresa')],
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('area_hectareas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='área (ha)')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fincas', to='organizacion.empresa')),
            ],
            options={
                'verbose_name': 'finca',
                'verbose_name_plural': 'fincas',
                'ordering': ['empresa', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nombre'), name='finca_unica_por_empresa')],
            },
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puntos_venta', to='organizacion.empresa')),
            ],
            options={
                'verbose_name': 'punto de venta',
                'verbose_name_plural': 'puntos de venta',
                'ordering': ['empresa', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nombre'), name='punto_venta_unico_por_empresa')],
            },
        ),
    ]
